#
#

#obj-$(CONFIG_PXA_U810)                           += lcd-tpo.o lcd_sharp.o

obj-$(CONFIG_PXA_U810)                      += lcd-lead.o
obj-$(CONFIG_PXA_U810)                     += lcd-xinli.o
obj-$(CONFIG_PXA_U880)                     += lcd_nt35580.o
obj-$(CONFIG_PXA_U880)                     += lcd_HX8363A.o
obj-$(CONFIG_PXA_U880)                     += lcd_HX8063A.o
obj-$(CONFIG_PXA_U880)                     += lcd_HX8369_HYIDIS.o
obj-$(CONFIG_PXA_U880)                     += lcd_HX8369_LG.o
obj-$(CONFIG_PXA_U802)                     += lcd-ili9325.o
obj-$(CONFIG_PXA_U802)                     += lcd-hx8347.o
obj-$(CONFIG_PXA_U812)                      += lcd_R61581.o
obj-$(CONFIG_PXA_U812)                      += lcd_Lead9481.o
obj-$(CONFIG_PXA_U830)                      += lcd_R61581.o
obj-$(CONFIG_PXA_U830)                      += lcd_Lead9481.o


