# Sensors Class Driver
obj-y 					+= sensors_class.o
obj-$(CONFIG_PXA_U880) 	+= alsps_i2c.o
obj-$(CONFIG_PXA_U880) 	+= isl29026.o
obj-$(CONFIG_PXA_U810) 	+= alsps_vir_i2c.o
obj-$(CONFIG_PXA_U812) 	+= alsps_vir_i2c.o
